import './help'
import './ls'
import './cd'
import './cat'
import './clear'
import './whoami'
import './about'
import './resume'
import './projects'

export { getCommand, listCommands } from './registry'
export { parseInput } from './parser'
export type { Command, CommandContext, CommandResult, OutputBlock, ParsedInput } from './types'
